name: CI - Maven + Testcontainers

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Confirm Docker socket (debug)
        run: ls -la /var/run/docker.sock || true

      - name: Run tests
        run: mvn -B -V test
